version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: td-backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: td-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
      VITE_IN_DOCKER: "1"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev -- --host 0.0.0.0 --port 8080
